name: check

on: [ push, pull_request ]

jobs:
  config:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.11' ]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install dependencies
        run: |
          pip install wheel xcffib mypy psutil
          pip install --no-cache --upgrade --no-build-isolation cairocffi
          pip install --no-build-isolation git+https://github.com/qtile/qtile.git@master
          pip install git+https://github.com/elParaguayo/qtile-extras@main

      - run: qtile --version

      - name: "cmd: mypy"
        if: success() || failure()
        run: mypy config.py

      - name: "cmd: python"
        if: success() || failure()
        run: python config.py

      - name: "cmd: qtile check"
        if: success() || failure()
        run: qtile check -c ./config.py
