name: Mypy
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Mypy
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.2
      - name: Install dependencies
        run: |
          pip install mypy
      - name: mypy
        run: |
          mypy config.py
