name: Mypy
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Qtile
    steps:
      - uses: actions/checkout@v1
      - name: Set up python 3.10.X
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.4
      - name: Install dependencies
        run: |
          pip install mypy qtile
      - name: Check config
        run: |
          mypy config.py
